### ISSUE TITLE
Add screenshots to the readme

### ISSUE THREAD

**Issue by ilovethensa** [matzipan/envoyer#272]
Adding screenshots of the app to the readme would allow people to see how it looks like without going trough the trouble of compilling it

**Comment by matzipan** [comment]
Hi,

Thanks for the interest. For the time being this will have to be limited to my fediverse posts, since things are in flow and changing all the time. Here's one of my more recent posts: https://hachyderm.io/@matzipan/111122679220536340

Version 0.4, 0.5 will likely see the application on flathub and there will be screenshots there for sure.
